### ISSUE TITLE
请问ghproxy.com是停运了吗？

### ISSUE THREAD

**Issue by lk101** [stilleshan/stilleshan#1]
尊敬的stilleshan您好，非常抱歉用这种方式打扰您（受我所在环境限制，我目前仅能通过github提issue的方式联系到您）

今天（2023-11-17）我在通过ghproxy.com下载PowerShell7的时候意外发现ghproxy.com无法访问了。
请问是有计划的关停了此服务，还是出现了什么异常情况？
像我这样的ghpxory使用者能够帮上什么忙吗？

等待您的回复，祝一切顺利！

**Comment by stilleshan** [comment]
被墙了
试试 mirror.ghproxy.com
